models:
  kimi-k2-instruct:
    backends:
      default:1: 
        base_url: https://cloud.infini-ai.com/maas
        url_path_chat: /v1/chat/completions
        # if not set, read from env var OCTOLLM_API_KEY
        # api_key: sk-xxxx
